services:
  - type: web
    name: laravel-ci-cd-demo
    plan: free
    branch: main
    rootDir: .
    dockerfilePath: Dockerfile
    runtime: docker
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: APP_KEY
        value: base64:7VEjRpN/VcJOxid5cLt34uXKdkwZCTiuNvmH3K2X7+U=
